apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubebooks
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubebooks
    spec:
      containers:
      - name: kubebooks
        image: jastr945/kubebooks:1.0
        imagePullPolicy: Always
        env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: postgres
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: secretkey
          - name: DJANGO_DEBUG
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: debug
          - name: DJANGO_AUTH0_KEY
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: authkey
          - name: DJANGO_AUTH0_SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: authsecret
        ports:
          - containerPort: 80
