apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubebooks
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubebooks
    spec:
      containers:
      - name: kubebooks
        image: jastr945/kubebooks:3.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
