apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: postgres

# apiVersion: extensions/v1beta1
#   kind: Deployment
#   metadata:
#     name: postgres
#   spec:
#     replicas: 1
#       template:
#         metadata:
#           labels:
#             name: postgres
#         spec:
#           containers:
#             - name: postgres
#               image: postgres
#               env:
#                 - name: POSTGRES_PASSWORD
#                   value: mysecretpassword
#               ports:
#                 - containerPort: 5432
#               volumeMounts:
#                 - mountPath: /var/lib/postgresql/data
#                 - name: pg-data
#           volumes:
#             - name: pg-data
#               emptyDir:
