version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: /etc/search_engine/env.conf
    ports:
      - "80:80"
    links:
      - db:db
      - elasticsearch:elasticsearch
    depends_on:
      - db
      - elasticsearch
  db:
    image: mariadb:10.1
    restart: always
    env_file: /etc/search_engine/env.conf
    volumes:
      - dbdata:/var/lib/mysql/data
  elasticsearch:
    image: elasticsearch
    container_name: elastic
    env_file: /etc/search_engine/env.conf
    volumes:
      - esdata:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
volumes:
  dbdata:
  esdata:
