version: '3'

services:
  db:
    image: postgres
    env_file: /etc/search_engine/env.conf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elastic
    env_file: /etc/search_engine/env.conf
    volumes:
      - esdata:/var/lib/elasticsearch/data:rw
    ports:
      - "9200:9200"
  web:
    build: .
    env_file: /etc/search_engine/env.conf
    ports:
      - "80:80"
    depends_on:
      - db
      - elasticsearch
