version: '2.1'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
        - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: exit 0

  app:
    container_name: kubeapp
    build: .
    ports:
      - 80:80
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_AUTH0_KEY=${DJANGO_AUTH0_KEY}
      - DJANGO_AUTH0_SECRET=${DJANGO_AUTH0_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /home/polina/projects/xperiments/djangokube/kubebooks:/usr/src/app
    links:
      - postgres
