# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import searchapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('body', models.CharField(default='', max_length=3000, null=True)),
                ('date', models.DateField()),
                ('source', models.CharField(default='', max_length=255, null=True)),
                ('img', models.FileField(upload_to=searchapp.models.upload_image)),
                ('slug', models.SlugField(default='', unique=True)),
                ('category', models.FileField(blank=True, choices=[('blog posts', 'blog posts'), ('articles', 'articles'), ('poems', 'poems')], default='', max_length=50, upload_to='')),
            ],
        ),
    ]
