# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import searchapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20171021_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.FileField(blank=True, default='', null=True, upload_to=searchapp.models.upload_image),
        ),
    ]
