# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20171021_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
