# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
